pipeline:
  build:
    image: node:10
    commands:
      - npm install
      - npm run build

  upload-to-s3:
    image: plugins/s3
    region: us-west-2
    acl: public-read
    encryption: AES256
    bucket: calculator.recruitng.endian.io
    source: dist/**/*
    strip_prefix: dist
