pipeline:
  build:
    image: node:10
    commands:
      - npm ci
      - npm run build:prod

  upload-to-s3:
    image: plugins/s3
    region: eu-west-2
    acl: public-read
    encryption: AES256
    bucket: endian.io
    target: /the-180/calculator
    source: dist/**/*
    strip_prefix: dist
